
version: '3.7'

services:
    # サービス名は自由に設定
    django:
        # docker-sharedディレクトリの中から`Dockerfile`を探す
        build: ./new-pointplus
        # サービス起動後に入力されるコマンドを設定
        command: python manage.py runserver 0.0.0.0:8000
        # データを永続化させる場合の設定。`host:container`でパスを記載
        volumes:
            - ./new-pointplus/:/new-pointplus/
        # 開放するポートを指定。`host:container`でポートを記載
        ports:
            - 8000:8000
        # 環境変数を指定
        environment:
            # 1ならデバックモード
            - DEBUG=1
        # setting.pyに記載されているSECRET_KEYを記入
            - SECRET_KEY=hoge

    db:
        build: ./mysql
        image: mysql/mysql-server:5.7
        restart: always
        environment:
          MYSQL_DATABASE: django_db
          MYSQL_USER: test
          MYSQL_PASSWORD: test
          MYSQL_ROOT_PASSWORD: root
        ports:
          - "3314:3306"
        volumes:
          - ./mysql/initdb.d:/docker-entrypoint-initdb.d
          - ./mysql/conf.d:/etc/mysql/conf.d
          - ./log/mysql:/var/log/mysql

    nginx:
        build: ./nginx
        ports:
            - 1337:80
        depends_on:
            - django
